### ISSUE TITLE
Pull in PSR-2 changes from cakephp/cakephp-codesniffer:master 

### ISSUE THREAD

**Issue by alecho** [loadsys/loadsys_codesniffer#14]

**Comment by jtyost2** [comment]
Note of things we don't want:

"The opening brace MUST go on its own line, and the closing brace MUST go on the next line following the body." Opening brace on the same line as the function name (unless multiple lines for the args as PSR2 covers)

And spaces, tabs for Loadsys forever.

**Comment by alecho** [comment]
Going to voice my disagreement with opening brace and tabs as @jtyost2 stated above. I think if we're going to adopt PSR-2, it should be fully and completely, without exceptions.

**Comment by jtyost2** [comment]
Why?

There is no good reason why we need to adopt PSR-2 100%. We aren't a framework and even members of the FIG aren't required to adopt PSR-2 or even adopt it a 100%.

Our code, especially code that is only in-house has no reason to adopt PSR-2 100%. Plus we had this discussion back a while ago regarding tabs vs. spaces and tabs won out. Why would we go back on a decision we made less than a year ago for no really good reason?

PSRs are only suggestions to the FIG and general PHP community but in way are they requirements either from the FIG onto the general PHP community or CakePHP to their users of the framework. This was the specific argument I made to CakePHP regarding the tabs vs. spaces and other things, CakePHP can choose to do something and we have 100% freedom to do something totally different if we want to.

The FIG doesn't even speak for the PHP community as a whole it speaks for the 30ish projects/frameworks/etc that are voting members and they disagree. It's not the PHP community as a whole, it's not the PHP core saying do this.

The benefit of us writing our own code for our use internally is that we can choose to adopt the standards or parts of a standard that we want. There is literally no benefit to our internal code conforming to an standard that we don't agree with.

If someone new comes onboard, it's not exactly like if we choose some modification of PSR-2 it would be complicated to explain or to grasp. I would imagine the vast majority of PHP devs aren't using PSR-2 as their formal code standard in-house anyways. Same with if any of projects wind up moving to another team or we are doing work with another team concurrently. In any of these cases the whole point of the code sniffer is it allows our code to be scanned and sniffed according to our arbitrary standards.

**Comment by beporter** [comment]
The problem with building an outline like PSR-* (by committee, no less) and agreeing on it as "a standard" is two-fold:

1. Just because it's "a standard" doesn't automatically mean it was created with wisdom and from experience.
1. Now that it's "a standard", you're pretty much stuck with any bad decisions you didn't realize when you created it, for all time, because people will throw fits if you keep changing things on them. (See the recent argument about deprecating `function ClassName()` PHP4-style constructors.)

I don't see any **practical** advantage to Loadsys tying themselves _strictly_ to _any_ standard. And I see potential *dis-*advantage in being "forced" to update otherwise readable and internally-consistent code to meet a standard solely because we've decided to hitch our wagon to someone else's horse. (We don't even get any say in what that standard consists of.)

I do see plenty of advantage of taking _cues_ from the majority where it serves our purposes (and those of our clients). This is what we've done historically, and what we currently do, to great effect, in my opinion. We're free to cherry pick the most helpful parts without arbitrarily feeling like we must comply with every edict handed down from a consortium that has no reason to act in our company's best interest.

![They're more like, guidelines](http://www.quickmeme.com/img/bf/bf5243ddc3ba9845c10dd0c97171af85bcdecb124870fb35350122b8b6a172c7.jpg)

**Comment by jtyost2** [comment]
Closed as part of the 3.x Release.
